### ISSUE TITLE
 Internal Server 500 "message":"Could not authenticate you." 

### ISSUE THREAD

**Issue by rrawann** [jaredhanson/passport-twitter#122]
Hello
I use passport-twitter with NestJs when signUp with twitter and I have my consumerKey and consumerSecret , but i got Internal Server 500 "message":"Could not authenticate you." how can fix it?

**Comment by jaredhanson** [comment]
This is caused by Twitter disabling API v1.1 access for the app.  It's not clear at all to me under what conditions Twitter chooses to do this (they've disabled a number of my apps).  You can check the status on Twitter's [developer portal](https://developer.twitter.com/en/portal/dashboard).

In any case, there's no issue with this strategy - it still works assuming the app is allowed API v1.1 access.  I'd recommend upgrading to API v2 and OAuth 2.0, since that seems more stable with the changes going on at Twitter currently.
