### ISSUE TITLE
Possible to do express+passport+twitter authentication without cookies?

### ISSUE THREAD

**Issue by zettam** [jaredhanson/passport-twitter#77]
^ as the question asks  - possible?
If so, a sample would be perfect!

**Comment by BryanConradHart** [comment]
I would also like to know.
I'm writing an API with restify/passport-restify. Since our API clients won't have cookies, I'm hoping to capture the twitter access token and issue my own token to our client.
I've got it working with passport-facebook, I was hoping that twitter would be similar, but I ran into this issue.

**Comment by jaredhanson** [comment]
Duplicate of #74
