### ISSUE TITLE
500 Error: failed to find request token in session

### ISSUE THREAD

**Issue by neojp** [jaredhanson/passport-twitter#8]

**Comment by championswimmer** [comment]
This is a very late answer, but I just figured another reason this can happen. When the guys who made express-session said that MemoryStore is not meant for production, they really meant it.

If you're using clustering, (pm2 or forever or running on Heroku), then memory based cookie storages have their own set of problems. You'll often loose cookies or corrupt them (because there are two or more separate processes on server side, not sharing common memory).

If you want to run your Node app with clusters, you need to use Redis or some DB-backed cookie storage
